<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Thomas</name>
   <tag></tag>
   <elementGuidId>46a9312f-c503-4776-9c05-618ed7349a5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.qbl-username-link.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='right-leftitem']/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f5c586f1-55e5-45a1-9cb1-c54fb1ee6604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbl-username-link ng-binding</value>
      <webElementGuid>a1110f02-0341-4ea5-8447-15966c85318c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thomas</value>
      <webElementGuid>87cc79bd-e65b-4797-8a81-c394ac30ec3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;right-leftitem&quot;)/div[@class=&quot;qbl-username&quot;]/a[@class=&quot;qbl-username-link ng-binding&quot;]</value>
      <webElementGuid>e01cd2eb-e50b-4e22-967c-58f34553175f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='right-leftitem']/div[4]/a</value>
      <webElementGuid>28b8866d-fae6-4954-92cb-fcb4b250f143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Thomas')]</value>
      <webElementGuid>31261940-049a-4ac5-b04d-b649cc65568b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YOUR TRUSTED FAMILY BANK'])[1]/following::a[3]</value>
      <webElementGuid>db99500a-090b-43a4-b0f6-4c196b772b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/preceding::a[1]</value>
      <webElementGuid>4b5a213a-ef7c-40d8-b530-f54a2ff8b833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/preceding::a[1]</value>
      <webElementGuid>430eb52e-2ce0-48f4-9039-1f8b8a993523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thomas']/parent::*</value>
      <webElementGuid>1fe9ace2-2511-40a9-8bae-ec7df1274287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[3]</value>
      <webElementGuid>66e7830d-a0da-4756-902d-8790539da4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>61b752fe-059b-4c40-938f-7906a5977de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Thomas' or . = 'Thomas')]</value>
      <webElementGuid>15023f22-059d-44bd-ba5f-e01cca968a57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
