<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Verify</name>
   <tag></tag>
   <elementGuidId>b024e9dd-5730-443c-8259-960166d4c8d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sub-qb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='sub-qb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>725d1edc-300f-445a-b14c-a808bfb9bffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sub-qb</value>
      <webElementGuid>168e10c7-73cb-4692-9dcd-67ff85360048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f66e7f50-6edb-4f53-826e-0fb9e0c6945c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>userCtrl.initiateBillPayment()</value>
      <webElementGuid>f1b99a0b-f513-4eb6-916f-769e4efe93c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbf-submit-button</value>
      <webElementGuid>82fab260-7dd5-48ae-8a18-ea0b7d8c66c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>bdc7b931-d568-44d0-8548-dd3d7e4858b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub-qb&quot;)</value>
      <webElementGuid>08634e74-fac4-4a7c-80fd-e07984bb53f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='sub-qb']</value>
      <webElementGuid>ec6b8eba-0d0b-425d-8636-fa501e7234bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bill-payment-btn']/div[2]/button[2]</value>
      <webElementGuid>5b843c43-fd09-4d9c-a9df-14433ea124ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>d0878e34-c99b-43c8-9908-61156829addc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer Date'])[1]/following::button[2]</value>
      <webElementGuid>df579032-c58a-4914-afe4-04ad773b302e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YOUR TRUSTED FAMILY BANK'])[2]/preceding::button[1]</value>
      <webElementGuid>a02530e9-5c71-4743-abbd-05bbfc3669a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>99148434-999e-49ea-b972-86c9648f2062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'sub-qb' and @type = 'submit' and (text() = 'Verify' or . = 'Verify')]</value>
      <webElementGuid>2cb6acb5-1070-4215-85d0-41c04a91e5a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
