<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Confirm</name>
   <tag></tag>
   <elementGuidId>08fb98e9-d6b8-4056-8342-9ac4ede46db9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sub-qb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='sub-qb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f426bf9d-4f59-4e42-a91e-4bf7977bd61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sub-qb</value>
      <webElementGuid>61500611-22fa-47aa-abb5-6027e9850817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>664417e4-571b-4a09-9cb4-eb1ca563596b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>userCtrl.verifyPaymentDetails()</value>
      <webElementGuid>1edb4c26-fded-4ab3-b537-e1129790cb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbf-submit-button</value>
      <webElementGuid>3a2d713f-d38b-40a4-9a1d-8b299d0bf231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>cbc75308-ad67-4941-a5be-c565409d033a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub-qb&quot;)</value>
      <webElementGuid>6e646073-9621-46aa-b95d-f9d22612671f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='sub-qb']</value>
      <webElementGuid>1b0c5f11-e970-402b-bd35-414268229389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bill-payment-btn']/div[2]/button[2]</value>
      <webElementGuid>7da8d3df-fc7b-44f9-bfc7-8806d25408e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>b7851b3f-4e62-4134-b54b-094e81969864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YOUR TRUSTED FAMILY BANK'])[2]/preceding::button[1]</value>
      <webElementGuid>5cc7272e-f310-4ab4-9b3a-577cb1ca13e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirm']/parent::*</value>
      <webElementGuid>c0e220fc-f2bb-447a-9bd7-6d4bb215c5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>08b3df9c-36ee-40c3-9ac4-3f734ab2cb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'sub-qb' and @type = 'submit' and (text() = 'Confirm' or . = 'Confirm')]</value>
      <webElementGuid>e5782744-4d0b-4223-a36d-34c027dcfd14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
