<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update Information</name>
   <tag></tag>
   <elementGuidId>a910da92-79f6-4394-a679-ee29c505e12e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sub-qb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='sub-qb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3b5aedd8-e4ca-42d9-9388-faf9dc49e073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sub-qb</value>
      <webElementGuid>d13d06c3-4910-4965-bf79-52c0803fa61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>64cfcef0-528e-4a2e-b20e-6ccee19f36e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>userCtrl.updateUserInfo()</value>
      <webElementGuid>2f4f4b4a-6ad0-4964-9ac4-9db25b00d6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbf-submit-button</value>
      <webElementGuid>77f1d852-3342-4e5f-a250-6e1776f96f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update Information</value>
      <webElementGuid>c0defc07-7f07-4344-b6e4-aecf917bd414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sub-qb&quot;)</value>
      <webElementGuid>1b31583a-0b09-492a-b0f3-4b6607a66fe2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='sub-qb']</value>
      <webElementGuid>3944f41c-7a63-4411-8077-519e485c557a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='two-btn']/button[2]</value>
      <webElementGuid>b29c2ebc-0bcb-4915-b052-098b837bb601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>4eff4d71-6083-4c05-ad8e-c1b450e305a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resident State'])[1]/following::button[2]</value>
      <webElementGuid>49f32c2f-a2ee-4ed9-a6c4-ec0f43f3efad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YOUR TRUSTED FAMILY BANK'])[2]/preceding::button[1]</value>
      <webElementGuid>e4fd0a10-d7c5-438f-b7a4-c80c52ebeb16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Update Information']/parent::*</value>
      <webElementGuid>781b6d97-4cf2-481d-93e4-d57a2f7c07d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>b3ec68cb-97ff-44fa-beb9-fe6273cb2625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'sub-qb' and @type = 'submit' and (text() = 'Update Information' or . = 'Update Information')]</value>
      <webElementGuid>9c93f623-afff-496e-a4b8-4e8eb153673e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
