<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Home</name>
   <tag></tag>
   <elementGuidId>e391251e-625c-4e36-a83f-ecfedcee418e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.qb-navbar-menuitem.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='qb-nav-margin']/div[3]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5c5f89b0-f07d-4f59-baca-c48e8302d6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qb-navbar-menuitem active</value>
      <webElementGuid>707fedd5-be28-4381-8302-79e79e087383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>mainCtrl.goToState('HomePage')</value>
      <webElementGuid>52d85c4e-a143-4347-ad91-0503bec9f5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>mainCtrl.isActiveState('HomePage') ? 'active' : ''</value>
      <webElementGuid>eb00e90b-6a3b-40fb-8e9d-7ac0fc3d0d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Home
                    </value>
      <webElementGuid>b1b8f6e7-44a3-49c5-87c0-cab203a31494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qb-nav-margin&quot;)/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;qb-navbar-menu&quot;]/div[@class=&quot;qb-navbar-menuitem active&quot;]</value>
      <webElementGuid>db4a7743-2fd7-48ce-9f90-feb025468a55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qb-nav-margin']/div[3]/div/div</value>
      <webElementGuid>45832c3f-4b53-403e-9681-c677e1f26067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YOUR TRUSTED FAMILY BANK'])[1]/following::div[3]</value>
      <webElementGuid>a87a99c8-18b5-499f-8f23-c5b94c864026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Card'])[1]/preceding::div[2]</value>
      <webElementGuid>aec51a87-a53a-49dc-83fc-515829c7cb8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home']/parent::*</value>
      <webElementGuid>a609846f-d204-4ae8-bb18-28e1101bcd5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div/div</value>
      <webElementGuid>329ac7b5-5cdf-4c23-a41f-d18a932839ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                        Home
                    ' or . = '
                        Home
                    ')]</value>
      <webElementGuid>7fabc82b-bc79-4351-a21e-f4ca54ab4109</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
