<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Why Invest</name>
   <tag></tag>
   <elementGuidId>0353f78d-38a2-41fd-9edd-c0bed951ce66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signin-carousel-first</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='signin-carousel-first']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>141aca5c-2019-477a-bdfb-b2ac89936bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signin-carousel-first</value>
      <webElementGuid>e9b6cc84-8e51-48f6-b2b0-ffe312ab82c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qb-carousel-tag</value>
      <webElementGuid>9f13cdbf-ed1f-4b03-925f-40f9c7622467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Why Invest?</value>
      <webElementGuid>0d8c7c88-114b-42c5-8826-bd800b89385d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signin-carousel-first&quot;)</value>
      <webElementGuid>0ea5639f-5522-48b5-97f7-c0f800030171</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='signin-carousel-first']</value>
      <webElementGuid>6430b708-ea3e-4d42-8390-37ad2c5d40c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qb-invest']/div</value>
      <webElementGuid>5987cf0c-5966-4ce4-bcc3-a0cdcfb70d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn about investing and how to find an advisor you trust'])[1]/following::div[3]</value>
      <webElementGuid>229bd2b0-e3db-4c49-9f02-32873808446e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more   >'])[4]/following::div[12]</value>
      <webElementGuid>21f62e82-b3c4-443a-89db-efbef6e3f338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compare ways to Invest'])[1]/preceding::div[1]</value>
      <webElementGuid>07992ff4-4c93-4188-926c-43ded40d6a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online investing with Q Bank'])[1]/preceding::div[2]</value>
      <webElementGuid>601424e1-950e-4547-b796-4c50ca66ee79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Why Invest?']/parent::*</value>
      <webElementGuid>ff65c2a1-aafe-4007-9312-23d0e4627dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/div[2]/div</value>
      <webElementGuid>d07d5eee-1182-4b82-92e1-2aaa0008de95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'signin-carousel-first' and (text() = 'Why Invest?' or . = 'Why Invest?')]</value>
      <webElementGuid>de3520e2-7607-4035-84d3-1602156f695c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
