<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mortgage</name>
   <tag></tag>
   <elementGuidId>2bfec02f-ce63-4cb0-9ac1-6412c9f463a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='signin-card-heading'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07a778b2-a1f6-44c4-9e72-f036d96ab5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signin-card-heading</value>
      <webElementGuid>33a51171-bfdd-4741-bc5a-e240bc09689c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qb-general-subheading</value>
      <webElementGuid>51bf8d0d-0610-48af-b3f7-aa5c2d02db27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Mortgage
                    </value>
      <webElementGuid>b55aa9ac-e9e9-4300-b8ab-b79e95f715cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signin-card-box&quot;)/div[@class=&quot;col-md-3 col-sm-6 col-xs-12&quot;]/div[@id=&quot;signin-card-heading&quot;]</value>
      <webElementGuid>c8c8e855-b1ef-4eb7-959a-92a6a93c9530</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='signin-card-heading'])[3]</value>
      <webElementGuid>910a96e4-e29c-4306-ad1c-abd4b8635863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signin-card-box']/div[3]/div[2]</value>
      <webElementGuid>75b6e806-606d-42d8-86ce-ac287dff7dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more   >'])[2]/following::div[3]</value>
      <webElementGuid>22c757cb-124a-4c8a-a256-0d9c2edf813a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick, hassle free loans with lowest interest rates for your dream car.'])[1]/following::div[4]</value>
      <webElementGuid>729bb409-e7fb-4df7-acbc-41ed8a9e1f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get a step-by-step guidance from an experienced mortgage banker.'])[1]/preceding::div[1]</value>
      <webElementGuid>f5022e51-1e36-420b-ab94-36b141092175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more   >'])[3]/preceding::div[2]</value>
      <webElementGuid>f85527a6-954f-48e5-b4eb-bb9bbfc92f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]</value>
      <webElementGuid>7ef6ebf1-700c-4532-80e9-28a1f15ebcf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'signin-card-heading' and (text() = '
                        Mortgage
                    ' or . = '
                        Mortgage
                    ')]</value>
      <webElementGuid>5bcc4fd4-47b1-490d-a1f0-75b100c03716</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
