<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_64BE1493F9B81691D3F9</name>
   <tag></tag>
   <elementGuidId>9312d03b-d789-4e4b-b3f9-86a8ae0544fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mobile-access-key</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mobile-access-key']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>79a6ef56-5fb2-4c80-b68c-a81467505a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbf-label ng-binding</value>
      <webElementGuid>9af85e29-5026-4af7-809f-696ead5f6520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobile-access-key</value>
      <webElementGuid>868fe781-ff1c-460c-877b-393787a92ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-init</name>
      <type>Main</type>
      <value>mobileAccessKey = userCtrl.getMobileAccessKey()</value>
      <webElementGuid>b88b1f11-841e-4042-b63c-2c43422d14e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    64BE1493F9B81691D3F9         
                </value>
      <webElementGuid>b7ed34c9-fe69-42a9-b9b4-999f343c63f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile-access-key&quot;)</value>
      <webElementGuid>007bb0e1-7da8-43de-a022-52eeaa36620d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mobile-access-key']</value>
      <webElementGuid>9b5adf33-6cbf-4cd5-8d17-13d3424b3f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user-mobile-key']/div[2]/div</value>
      <webElementGuid>fa0f7502-77a3-490a-a9b6-65b3d92d3c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile Access Key'])[1]/following::div[2]</value>
      <webElementGuid>9a214ac1-f642-4d6b-88b1-102989c17675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone'])[1]/following::div[8]</value>
      <webElementGuid>5fdefd33-6967-4dd7-b729-49c374edff4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resident State'])[1]/preceding::div[2]</value>
      <webElementGuid>411dc76f-7ad2-4a53-9f34-6d9113a06bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[9]</value>
      <webElementGuid>0a0e1add-ecca-468d-baf0-649324fd4518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='64BE1493F9B81691D3F9']/parent::*</value>
      <webElementGuid>0ebf54b7-6953-4206-bafd-085f1d9279a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div</value>
      <webElementGuid>14fe304b-1f99-4c1d-b01f-5f3ea658b08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mobile-access-key' and (text() = '
                    64BE1493F9B81691D3F9         
                ' or . = '
                    64BE1493F9B81691D3F9         
                ')]</value>
      <webElementGuid>861caf94-5023-4bcb-8316-32f6018af512</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
