<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Verify</name>
   <tag></tag>
   <elementGuidId>92edf1bb-d082-46c2-a4aa-1b0ac2e71804</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#each-box > #box-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='box-heading'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a3d2354d-ae74-423e-895b-2ebd141724da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>box-heading</value>
      <webElementGuid>6071ecad-7b68-4383-83db-502a7f388cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbf-stageName</value>
      <webElementGuid>19e22a03-d4c6-46e0-8a3a-8cd078132baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>99b84d23-d46c-4718-a620-3cf19449a96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bill-head-box&quot;)/div[@id=&quot;each-box&quot;]/div[@id=&quot;box-heading&quot;]</value>
      <webElementGuid>ed06fca9-86c8-43df-9fbd-e038cf896eb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='box-heading'])[2]</value>
      <webElementGuid>8d9d4a97-e99e-4876-913d-1a39e7edb674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='each-box']/div[2]</value>
      <webElementGuid>c960e881-81a3-45ee-adcd-9d98dc79c011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fill Details'])[1]/following::div[3]</value>
      <webElementGuid>c2eac8db-963c-4649-aa9e-55053b4a0112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bill Payments'])[2]/following::div[7]</value>
      <webElementGuid>b5151950-e1b7-469c-b339-94975342f5d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation'])[1]/preceding::div[2]</value>
      <webElementGuid>464632dc-77bf-4ed0-88d0-922652047a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer from'])[1]/preceding::div[4]</value>
      <webElementGuid>20414c41-85f3-42c6-972e-bbac47b215f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verify']/parent::*</value>
      <webElementGuid>a15487da-6f6a-42fc-8a0d-45532b7f62ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]</value>
      <webElementGuid>1ade9b81-4aeb-4a4c-beb8-ab0ef61c0af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'box-heading' and (text() = 'Verify' or . = 'Verify')]</value>
      <webElementGuid>86c18b99-c10f-41ee-97f7-5b6116482e53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
