<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Invest</name>
   <tag></tag>
   <elementGuidId>b0c57923-37c5-4ac3-ba3c-915d5ac70372</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='signin-card-heading'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cf3471c1-fae8-4723-95aa-c72450deb1d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signin-card-heading</value>
      <webElementGuid>5f56cd5e-af06-4144-83d0-99f61335db07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qb-general-subheading</value>
      <webElementGuid>8646d644-75cc-4b26-9cbe-ee7cc14a7532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Invest
                    </value>
      <webElementGuid>08e0db7b-f755-4e65-85fa-b5f38d3928a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signin-card-box&quot;)/div[@class=&quot;col-md-3 col-sm-6 col-xs-12&quot;]/div[@id=&quot;signin-card-heading&quot;]</value>
      <webElementGuid>dd17954b-76e2-4298-9416-7c39d06a2a54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='signin-card-heading'])[4]</value>
      <webElementGuid>d7dbcc5b-a3db-4486-949c-916804ee8963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signin-card-box']/div[4]/div[2]</value>
      <webElementGuid>e7bafa39-5021-45be-a598-33091d02ee4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more   >'])[3]/following::div[3]</value>
      <webElementGuid>fc5fb5f0-8c41-4827-adfb-12d7d5aed922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get a step-by-step guidance from an experienced mortgage banker.'])[1]/following::div[4]</value>
      <webElementGuid>154a2ea4-4ba0-4143-bcf6-7f064d7bbe23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal, ongoing guidance and advice to our broad range of products.'])[1]/preceding::div[1]</value>
      <webElementGuid>1e679f68-c982-4889-9e63-fef8989f1fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more   >'])[4]/preceding::div[2]</value>
      <webElementGuid>e28c152d-32d5-472d-8ca0-2aac1411e1d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[4]/div[2]</value>
      <webElementGuid>026354c3-9257-4006-a688-4c38480f86df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'signin-card-heading' and (text() = '
                        Invest
                    ' or . = '
                        Invest
                    ')]</value>
      <webElementGuid>4907eac0-f79a-4167-9ab7-352e9c746f04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
