<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Auto Loan</name>
   <tag></tag>
   <elementGuidId>78ca0c8d-6db2-40f2-987b-342b4c2d3e88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='signin-card-heading'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b986ea41-0b0c-49f6-adca-719aef1dc092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signin-card-heading</value>
      <webElementGuid>60a56acb-4f58-4f70-ab7a-2618255520f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qb-general-subheading</value>
      <webElementGuid>6625d0f9-e5fb-421b-bcbe-208ef9491859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Auto Loan
                    </value>
      <webElementGuid>2d50dbf4-d1f6-4d0d-a834-e4a641aa0255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signin-card-box&quot;)/div[@class=&quot;col-md-3 col-sm-6 col-xs-12&quot;]/div[@id=&quot;signin-card-heading&quot;]</value>
      <webElementGuid>21ce046f-630e-413a-b9be-72eaac7a0493</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='signin-card-heading'])[2]</value>
      <webElementGuid>04a28677-b2be-4f42-807c-b5bd119a3837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signin-card-box']/div[2]/div[2]</value>
      <webElementGuid>e94299ca-c84d-4d08-a21d-2fbd501e31c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more   >'])[1]/following::div[3]</value>
      <webElementGuid>a890f73c-d833-4813-9ff8-d4a19365f2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A credit card for every need. Extreme convenience &amp; unmatched benefits.'])[1]/following::div[4]</value>
      <webElementGuid>1a19a172-b769-4d2e-831b-ec3d9c5002c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick, hassle free loans with lowest interest rates for your dream car.'])[1]/preceding::div[1]</value>
      <webElementGuid>000a3819-84bd-4033-90e7-c7a7ff8c0cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more   >'])[2]/preceding::div[2]</value>
      <webElementGuid>5158a1dc-c414-47d6-88f1-2f2cd95d67fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]</value>
      <webElementGuid>16bffc80-c19a-41e6-9607-6797e40f4719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'signin-card-heading' and (text() = '
                        Auto Loan
                    ' or . = '
                        Auto Loan
                    ')]</value>
      <webElementGuid>68b90947-6f6a-4d8c-867e-78b4a12ac97c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
