<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Fill Details</name>
   <tag></tag>
   <elementGuidId>6abfbc7c-c156-4e71-8928-db7b76205fc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#box-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='box-heading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>da99244f-31bc-45cd-81d8-ef5964b72250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>box-heading</value>
      <webElementGuid>b93d8ad4-92ce-46ca-a2e2-0b9854105e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbf-stageName</value>
      <webElementGuid>92bf47a6-00ab-49f2-8f1d-557b86bd1506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fill Details</value>
      <webElementGuid>3cd07387-39a6-4d7a-9ea0-1a2348e05ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;each-box-1&quot;)/div[@id=&quot;box-heading&quot;]</value>
      <webElementGuid>b28da377-dea6-4439-bdf8-184f92039ee1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='box-heading']</value>
      <webElementGuid>aebbdf2b-3996-442f-bea8-58b3a05d64d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='each-box-1']/div[2]</value>
      <webElementGuid>cc7187a2-7229-41b7-b41c-bbdb2c238b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bill Payments'])[2]/following::div[4]</value>
      <webElementGuid>37583b81-8f81-42cd-a89d-e4b083d8189e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Cheque book'])[1]/following::div[7]</value>
      <webElementGuid>3b8ec81d-4594-46e3-b6a6-5a8f21a9dccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verify'])[1]/preceding::div[2]</value>
      <webElementGuid>24a991fa-c476-44cd-ac61-1df5b437e75f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation'])[1]/preceding::div[5]</value>
      <webElementGuid>e1fa3f5b-7627-4153-a2b8-e3b6141b5b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fill Details']/parent::*</value>
      <webElementGuid>803b801b-1b56-4bb9-8842-0841e7b05cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>6d6e2539-9769-4eb0-8662-70452b809da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'box-heading' and (text() = 'Fill Details' or . = 'Fill Details')]</value>
      <webElementGuid>e1711de3-689d-41da-9e54-9599c495ac75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
