<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Show</name>
   <tag></tag>
   <elementGuidId>3a7fcca9-b1f5-4720-a16d-8886384cb5a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.qb-showmodal-btn.qb-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='rev-padding']/div)[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ae735f02-b593-481c-85a2-36dd344b4428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qb-showmodal-btn qb-right</value>
      <webElementGuid>71e175d9-2866-4629-8558-83e1a4b4cf1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>mainCtrl.goToAccount($index)</value>
      <webElementGuid>16c4203d-3ef9-4c04-8e85-2eca125d52d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show</value>
      <webElementGuid>3bd34fd0-a3f1-4fd0-b7eb-d719a7263050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qb-info-container&quot;)/div[@id=&quot;qbl-card-sec&quot;]/div[@class=&quot;qb-box-body&quot;]/div[@id=&quot;ac-details&quot;]/div[2]/div[@id=&quot;rev-padding&quot;]/div[@class=&quot;qb-showmodal-btn qb-right&quot;]</value>
      <webElementGuid>e285c1b6-1e56-43a1-bffc-d798da6eab14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='rev-padding']/div)[4]</value>
      <webElementGuid>978d1b50-cbd9-4ee7-852a-fa9639621b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$17,879.00'])[1]/following::div[2]</value>
      <webElementGuid>0be4774d-66fa-4cf0-b66c-6b0ac2405b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::div[4]</value>
      <webElementGuid>e4eb5848-101e-40d5-836c-e3a5f1856795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Savings'])[1]/preceding::div[3]</value>
      <webElementGuid>7d972637-37fa-421d-b041-e4c6bfd78375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly Savings account'])[1]/preceding::div[5]</value>
      <webElementGuid>24e86e9e-6ffb-4241-974f-f277d064c785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Show']/parent::*</value>
      <webElementGuid>7598688e-de00-4f86-9835-4f98bae1740a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>3ba90499-10e8-47e8-a50d-57a96a1154ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Show' or . = 'Show')]</value>
      <webElementGuid>2831060d-175a-43c5-be88-662a8947c999</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
