<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NO</name>
   <tag></tag>
   <elementGuidId>bbf55dff-a721-4f73-8b54-ff0880ebf0d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.qbb-searchresult-taghead.safebox.ng-binding.salmon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='qbb-safe-boxes']/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1c722c3a-494e-4b53-9824-f7b8c1b20977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbb-searchresult-taghead safebox ng-binding salmon</value>
      <webElementGuid>6af80fc6-1841-4693-8f25-f5822b80242f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>branch.safe_box === 'YES' ? 'seagreen': 'salmon'</value>
      <webElementGuid>7983a1f2-ff0c-4af5-9a2e-8f0d037e41f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    NO
                                </value>
      <webElementGuid>859d7822-2ecd-4c35-860b-d269681cec79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-body&quot;)/div[@class=&quot;container-fluid qbb-searchresults-container ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10&quot;]/div[@class=&quot;qbb-searchresult ng-scope border&quot;]/div[@id=&quot;qb-branch-atm&quot;]/div[@id=&quot;qbb-safe-boxes&quot;]/div[@class=&quot;col-md-9 qb-no-xpadding&quot;]/div[@class=&quot;qbb-searchresult-taginfo&quot;]/div[@class=&quot;qbb-searchresult-taghead safebox ng-binding salmon&quot;]</value>
      <webElementGuid>7d8f07f4-38a1-4219-803e-75fb16b3fe48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qbb-safe-boxes']/div[2]/div/div</value>
      <webElementGuid>6f7e014d-2eb2-4a07-ba1a-8c67037d4d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXPRESS BANKING'])[1]/following::div[6]</value>
      <webElementGuid>2fef8ae0-6dbe-4140-846e-7d09af148ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YES'])[1]/following::div[7]</value>
      <webElementGuid>87de5cae-2d5b-4e81-9eb8-670d877b4590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAFE BOXES'])[1]/preceding::div[1]</value>
      <webElementGuid>44a1cd7b-22f8-439f-8172-6d978fe0bdc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[2]/preceding::div[4]</value>
      <webElementGuid>a838efdd-1195-4b26-acf6-f94a97ae1c55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NO']/parent::*</value>
      <webElementGuid>fb90043c-87e8-464f-a4b2-56434b24808f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div[3]/div[2]/div/div</value>
      <webElementGuid>01b30d5e-f656-4a14-8a19-8cf8b4648522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                    NO
                                ' or . = '
                                    NO
                                ')]</value>
      <webElementGuid>89c86c27-1ae0-4f6e-b8e7-bf14f3a27ce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
