<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Confirmation</name>
   <tag></tag>
   <elementGuidId>2802472f-c77e-44d8-8266-266db3c9e395</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='box-heading'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>29afcc45-1b39-4037-8c48-107a2fdf51e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>box-heading</value>
      <webElementGuid>1428c20f-851a-4296-b4e0-217a046df864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbf-stageName</value>
      <webElementGuid>3a90a819-a1f9-41ac-a34e-86380835d84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Confirmation</value>
      <webElementGuid>3bef1cc0-4d76-47fe-baa4-4022b3b986e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bill-head-box&quot;)/div[@id=&quot;each-box&quot;]/div[@id=&quot;box-heading&quot;]</value>
      <webElementGuid>7d39a7bf-03c3-427e-bae2-898ad7114b54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='box-heading'])[3]</value>
      <webElementGuid>092e3317-1d32-4f06-8ad0-c307bf142f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='each-box']/div[2])[2]</value>
      <webElementGuid>642a73e8-4ca1-46b1-87df-0814e9b295e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verify'])[1]/following::div[3]</value>
      <webElementGuid>4e3c8b8f-c275-4a75-9fb4-78a3511c0879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fill Details'])[1]/following::div[6]</value>
      <webElementGuid>17e3d5b3-cc60-4685-bbe2-d2a1e2655940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer from'])[1]/preceding::div[1]</value>
      <webElementGuid>e5ea92f7-df6a-4e9c-8727-1984c856bcc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Bill'])[1]/preceding::div[6]</value>
      <webElementGuid>98c78377-0719-4fe4-a405-ef78738cbf5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Confirmation']/parent::*</value>
      <webElementGuid>25457069-1dd9-4c28-a214-91dd37af09ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[3]/div[2]</value>
      <webElementGuid>8d07eace-e25d-41bf-91fd-c0ad2faf9795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'box-heading' and (text() = 'Confirmation' or . = 'Confirmation')]</value>
      <webElementGuid>b8f1a503-08e0-47a9-9851-bb42f7401aa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
