<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Qbank</name>
   <tag></tag>
   <elementGuidId>d606a62b-18f0-4aa5-8226-56d40344e805</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-body']/div[2]/div/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4811cf75-66be-4ead-b719-9f1d3a454839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbb-searchresult-heading ng-binding</value>
      <webElementGuid>4eaf7fd5-ed03-4ecd-9508-e31a7ca67539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Qbank
                </value>
      <webElementGuid>bb03157f-6c14-4aae-a623-53d598008df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-body&quot;)/div[@class=&quot;container-fluid qbb-searchresults-container ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10&quot;]/div[@class=&quot;qbb-searchresult ng-scope border&quot;]/div[@class=&quot;qbb-searchresult-heading ng-binding&quot;]</value>
      <webElementGuid>fa7eec6e-c2fb-4a5d-b6bf-05b1495f3630</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-body']/div[2]/div/div[2]/div[2]/div</value>
      <webElementGuid>90c11c34-6881-42b3-bf99-9a7a63226344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DRIVE UP'])[1]/following::div[2]</value>
      <webElementGuid>bc3bbbbe-804c-483e-8acd-309142c20c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[2]/following::div[3]</value>
      <webElementGuid>3d3bcd96-b714-48f9-93f7-3f38379852b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anniversary'])[1]/preceding::div[1]</value>
      <webElementGuid>20321ee1-8244-4c42-bd98-434067e6959e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El Triunfo'])[1]/preceding::div[3]</value>
      <webElementGuid>0113d819-9086-420b-ad96-277e26c8ea2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div</value>
      <webElementGuid>f136f4d5-7824-49d3-bc1d-43757afe0447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                    Qbank
                ' or . = '
                    Qbank
                ')]</value>
      <webElementGuid>9b8d1510-ab82-45aa-8a29-4426ee908955</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
