<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Branches</name>
   <tag></tag>
   <elementGuidId>a0f02335-67e9-46bc-9632-859f762951ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='qb-nav-margin']/div[3]/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b064638a-73bf-428c-93d2-2c53c16660d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qb-navbar-menuitem</value>
      <webElementGuid>cc7fd621-ea59-4d87-8796-4b17f0fb7135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>mainCtrl.goToState('BranchesPage')</value>
      <webElementGuid>b5c09401-de30-4aef-b612-bebb8eb2d347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>mainCtrl.isActiveState('BranchesPage') ? 'active' : ''</value>
      <webElementGuid>3b6123af-1fb2-4b36-a0fa-60444c52d145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Branches
                    </value>
      <webElementGuid>1878f50d-d338-4144-aa3c-815e52697af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qb-nav-margin&quot;)/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;qb-navbar-menu&quot;]/div[@class=&quot;qb-navbar-menuitem&quot;]</value>
      <webElementGuid>3b82f629-36ff-4da6-a127-f35b3f010a1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qb-nav-margin']/div[3]/div/div[3]</value>
      <webElementGuid>a33f9219-dead-4a8a-9c4f-245edfe15340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invest'])[1]/following::div[1]</value>
      <webElementGuid>c7f799e8-bd1f-45e8-b8be-27d6ef940376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mortgage'])[1]/following::div[2]</value>
      <webElementGuid>6834856d-23b1-4bce-b3e3-4c266ce3e8c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learning center'])[1]/preceding::div[1]</value>
      <webElementGuid>973c6f80-7318-46ec-a447-902a16879a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test App'])[1]/preceding::div[2]</value>
      <webElementGuid>60737ff9-220c-4c17-bbf1-1060cd37bbe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Branches']/parent::*</value>
      <webElementGuid>c5e53a79-22f0-41bf-9cd8-b58c012d51f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div[3]</value>
      <webElementGuid>eb06ca44-ebf0-46b6-8ef5-7e2486d0b4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                        Branches
                    ' or . = '
                        Branches
                    ')]</value>
      <webElementGuid>f3be3a11-3704-45fd-ab13-b5b569e33e71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
