<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Credit Card</name>
   <tag></tag>
   <elementGuidId>cad86617-2da9-4250-8189-5a2e0295bf66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.qb-navbar-submenuitem</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='qb-nav-margin']/div[3]/div/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c0f46dac-adf8-4b9b-9c57-575d7d2d61d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qb-navbar-submenuitem</value>
      <webElementGuid>2e2598d2-43c3-4382-9afe-4667e9454e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>mainCtrl.goToState('Product.CCHome')</value>
      <webElementGuid>929ae422-de8c-4813-abf1-2fe755473335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Credit Card
                            </value>
      <webElementGuid>fdf3e15f-31fc-403e-9fff-0dbbc0a2e0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qb-nav-margin&quot;)/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;qb-navbar-menu&quot;]/div[@class=&quot;qb-navbar-menuitem&quot;]/div[@class=&quot;qb-navbar-submenu&quot;]/div[@class=&quot;qb-navbar-submenuitem&quot;]</value>
      <webElementGuid>42a7f9a7-712d-46a8-8ad8-dcf91375a510</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qb-nav-margin']/div[3]/div/div[2]/div/div[2]</value>
      <webElementGuid>65c97cfe-f03c-4820-bf51-09de1178f85d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::div[4]</value>
      <webElementGuid>7937e3ee-0755-44d1-9485-ba75b7274f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Loan'])[1]/preceding::div[1]</value>
      <webElementGuid>dc774095-cadf-47c6-821f-93cbf7ab4fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mortgage'])[1]/preceding::div[2]</value>
      <webElementGuid>3be2d593-fa26-4bc3-ad88-e3209ebf8804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Credit Card']/parent::*</value>
      <webElementGuid>2ba9eeef-001a-4acf-8f08-dd11faafa429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/div/div[2]/div/div[2]</value>
      <webElementGuid>5bfe9f6a-2f19-4d40-9fd9-c144bc3f649f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                Credit Card
                            ' or . = '
                                Credit Card
                            ')]</value>
      <webElementGuid>11893fa7-daf0-47d9-83ab-30c26e48f351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
