<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sat-Sun  Closed_bank-logo</name>
   <tag></tag>
   <elementGuidId>22ecb3a7-efe4-43a7-9d23-f0e6af92e296</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.qbb-searchresult-tagimage > #bank-logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='bank-logo'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2fa860d2-66f4-4f1f-813a-1c662decf1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bank-logo</value>
      <webElementGuid>2f75b803-35f9-45bb-98b0-702944cf0f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>client/images/branches/atm.png</value>
      <webElementGuid>df81267a-ade8-42b6-92b1-8878c36d4358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-body&quot;)/div[@class=&quot;container-fluid qbb-searchresults-container ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10&quot;]/div[@class=&quot;qbb-searchresult ng-scope border&quot;]/div[@id=&quot;qb-branch-atm&quot;]/div[@id=&quot;qbb-first-box&quot;]/div[@class=&quot;col-md-5&quot;]/div[@class=&quot;qbb-searchresult-tagimage&quot;]/img[@id=&quot;bank-logo&quot;]</value>
      <webElementGuid>cfb11ced-c253-44de-af28-ab1c72c9bfae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='bank-logo'])[2]</value>
      <webElementGuid>d5aa337c-8eaf-4d27-9274-60539d96ab98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qbb-first-box']/div/div/img</value>
      <webElementGuid>c59212b5-0a1f-4295-847c-eba88c3e4c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>6d5ac5e9-8c13-493f-a201-afad3c5cd1db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'bank-logo' and @src = 'client/images/branches/atm.png']</value>
      <webElementGuid>71b4ab33-bce5-468a-8f61-28b50473a7d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
