<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SAFE BOXES_bank-logo</name>
   <tag></tag>
   <elementGuidId>d2dbb0f0-e6a0-41ae-91db-0d45a4108786</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qb-last-box > div.col-md-3.qb-no-xpadding > div.qbb-searchresult-tagimage > #bank-logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='bank-logo'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c24c7827-8edf-45d8-9488-e44871923aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bank-logo</value>
      <webElementGuid>9400c55c-70cb-4ee3-b96b-2e4190ece278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>client/images/branches/driveup.png</value>
      <webElementGuid>7f73f636-1ee0-4cef-94c8-3c56b134301f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-body&quot;)/div[@class=&quot;container-fluid qbb-searchresults-container ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10&quot;]/div[@class=&quot;qbb-searchresult ng-scope border&quot;]/div[@id=&quot;qb-branch-atm&quot;]/div[@id=&quot;qb-last-box&quot;]/div[@class=&quot;col-md-3 qb-no-xpadding&quot;]/div[@class=&quot;qbb-searchresult-tagimage&quot;]/img[@id=&quot;bank-logo&quot;]</value>
      <webElementGuid>d33a67c9-4810-439c-9c2b-500f061b6fbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='bank-logo'])[5]</value>
      <webElementGuid>9df461bd-e40e-4396-8fd9-21efa9b3120a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qb-last-box']/div/div/img</value>
      <webElementGuid>68b3f1f2-95e0-407a-97e7-ab0dec1f98d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/img</value>
      <webElementGuid>d71c7f3c-6311-43d3-af74-92235e4447f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'bank-logo' and @src = 'client/images/branches/driveup.png']</value>
      <webElementGuid>b5e2b7e3-adec-4166-933c-01519304b06b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
