<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>82de7c51-b5e8-4be2-aa93-e05e69c5b360</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-body']/div/div[2]/div/div[2]/div[4]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6653f67d-fe81-4d54-96ae-4800cdea345c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>client/images/creditcard/cc_all.png</value>
      <webElementGuid>96a9d13c-afea-41e9-97f4-171a0555a1e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-body&quot;)/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;container-fluid qbp-menu ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-10 col-sm-10 col-xs-10&quot;]/div[@class=&quot;col-md-3 col-sm-6 col-xs-12 qb-center&quot;]/div[@class=&quot;qbp-menu-item&quot;]/img[1]</value>
      <webElementGuid>6e616e59-d555-4a71-82cf-084dbbd49f49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-body']/div/div[2]/div/div[2]/div[4]/div/img</value>
      <webElementGuid>55ad55da-b154-419c-b7f1-ded7724be5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/img</value>
      <webElementGuid>6ca2270c-1032-4465-93c0-a5a9d0aec6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'client/images/creditcard/cc_all.png']</value>
      <webElementGuid>8c3f18e4-f663-4a4d-be1f-74dd8f016069</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
