<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Learn more_signin-logo</name>
   <tag></tag>
   <elementGuidId>7a925664-59e3-4e3d-86e8-ee95e9a54f71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='signin-logo'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6e0162c7-b3e3-4a6e-aef1-d2ee367f7384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signin-logo</value>
      <webElementGuid>e642805e-2be3-4f44-b547-7c8baf9799a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>client/images/homepage/mortgage.png</value>
      <webElementGuid>7e481012-6586-4655-b4ef-f7a07823319e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signin-card-box&quot;)/div[@class=&quot;col-md-3 col-sm-6 col-xs-12&quot;]/div[@class=&quot;qb-category-icon&quot;]/img[@id=&quot;signin-logo&quot;]</value>
      <webElementGuid>e88db1cc-8110-447a-805c-ffff49e4eccb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='signin-logo'])[3]</value>
      <webElementGuid>1fa71709-899c-41a9-ad15-aa6270d70953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='signin-card-box']/div[3]/div/img</value>
      <webElementGuid>154a137c-f7a7-4254-969a-edca97ac2c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/img</value>
      <webElementGuid>37522d23-c0b4-4d9b-bf26-c2ed4ef9ee75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'signin-logo' and @src = 'client/images/homepage/mortgage.png']</value>
      <webElementGuid>a3cbaece-7568-41db-a739-bbf767af68af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
