<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Corporate Banking_qb-username</name>
   <tag></tag>
   <elementGuidId>ab8cbb1c-5520-450a-b868-7947436d493e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qb-username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='qb-username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43845b4b-7b8b-4ca0-8e06-cdf6c28edf9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>abfaeebf-3068-4aa6-b700-182554c167a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qb-username</value>
      <webElementGuid>4de880eb-0cf0-4b94-80ab-642aa5833674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>51a68a0b-dd96-42f8-83c2-404fb36a6ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>08c3592b-6f6c-4b2b-aa02-49cc801c4788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qb-signin-input ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>f3d9b3a8-1837-4e65-8d28-b9bdf082fed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qb-username&quot;)</value>
      <webElementGuid>1a2fa4b3-977f-46e9-8f3a-e26740793fce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qb-username']</value>
      <webElementGuid>3425d35c-6775-4534-bd4a-2682ac8ad4ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qb-login-container']/div/div[2]/div/div[2]/div/form/div[3]/input[2]</value>
      <webElementGuid>1ee66c7f-3208-4d31-b16e-2ed91168e642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input[2]</value>
      <webElementGuid>f6b25212-18b7-4d7b-9729-d3ab38f70101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'qb-username' and @placeholder = 'Username']</value>
      <webElementGuid>8314a155-622f-49ae-9c5d-5bfd2fd51702</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
