<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Memo_qbf-memo-input</name>
   <tag></tag>
   <elementGuidId>d450efca-7f9f-46c4-a50b-d149a7e5efb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qbf-memo-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='qbf-memo-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4785dfb-70cf-4cee-9251-7f3b6bbd124d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qbf-memo-input</value>
      <webElementGuid>f50969c4-55df-43e9-83a1-9ed980dec710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbf-input small ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>ec40981c-3796-4e9f-b967-16d575d3c64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>userCtrl.newTransaction.description</value>
      <webElementGuid>1078393d-9ccf-4cbd-96d2-bd0665c1e905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba0dfa87-b3dd-4052-9d6e-ef2fdfe2b63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qbf-memo-input&quot;)</value>
      <webElementGuid>abc61ecc-58ec-4e6e-ae9b-bd14dae848da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qbf-memo-input']</value>
      <webElementGuid>ea9e0f56-4d87-4360-8e7b-b60307be58c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='qb-bil-input']/input)[3]</value>
      <webElementGuid>2ddabdbe-67c6-4df1-bf96-0c91382124b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>80c47c67-578b-4cdd-9ad5-9197dd2ac2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'qbf-memo-input' and @type = 'text']</value>
      <webElementGuid>c52a1c45-c99c-4bd6-8a22-7f7f8bbea375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
