<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amount ()_qbf-amount-input</name>
   <tag></tag>
   <elementGuidId>a904c3f3-08c5-44cd-9b9f-c66882b50ce1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qbf-amount-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='qbf-amount-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8f4b5e7-c944-4104-ac8b-92bf95432b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qbf-amount-input</value>
      <webElementGuid>1bee384c-4e51-4638-b862-344d715802aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qbf-input small ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>f4fb561c-e753-4864-98d0-9e6aca3d34b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7d847018-ed9d-490e-a33d-8ef309a405f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>userCtrl.newTransaction.amount</value>
      <webElementGuid>51a7f671-e480-415d-9388-47d2cc6518ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>userCtrl.purposeOfAmount()</value>
      <webElementGuid>f9d7ce8c-1079-4abd-8091-edce979cbf55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qbf-amount-input&quot;)</value>
      <webElementGuid>a4412729-bd3e-4ec4-ac43-b7a015b18211</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qbf-amount-input']</value>
      <webElementGuid>2f8901d3-ba8a-4ddd-a481-a32a9db8b103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='qb-bil-input']/input</value>
      <webElementGuid>32a75b28-1563-4070-bd28-71cff5355505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f01c19e9-3ad3-472b-ab9d-d8a3e1b0d965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'qbf-amount-input' and @type = 'text']</value>
      <webElementGuid>8b9aec3b-a263-48d0-9d28-afa527600053</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
