<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Customer SupportShould you experience a_8c03a2</name>
   <tag></tag>
   <elementGuidId>be60ae41-2d92-4744-8c0f-74a596272d64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-support</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>928914d4-a336-41f1-8fef-a1955cbcdbf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-support</value>
      <webElementGuid>c88df1ae-1bb4-4938-a126-a3e60138b5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer SupportShould you experience any issues, please do not hesitate to contact us on  ossupport@orangehrm.com  We will be delighted to help.</value>
      <webElementGuid>42a5e1c6-9395-41c4-910c-91242aaff7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-card-container&quot;]/div[@class=&quot;orangehrm-support&quot;]</value>
      <webElementGuid>eadcf9fe-5ce7-4615-97ea-e9d76c919faf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>a03a731b-4787-4ee4-92a3-cf4c599c1b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OrangeHRM, Inc'])[1]/preceding::div[4]</value>
      <webElementGuid>08afb14f-19ca-4716-8e2b-2e860ec25fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div</value>
      <webElementGuid>0b363e6c-8f31-47c7-877a-00abeb0f4f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Customer SupportShould you experience any issues, please do not hesitate to contact us on  ossupport@orangehrm.com  We will be delighted to help.' or . = 'Customer SupportShould you experience any issues, please do not hesitate to contact us on  ossupport@orangehrm.com  We will be delighted to help.')]</value>
      <webElementGuid>d56f1b8c-9c6e-4aa5-b4c3-4092e3d6d892</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
